### ISSUE TITLE
Missing git in environment is not handled gracefully

### ISSUE THREAD

**Issue by mweinelt** [supakeen/steck#12]
```pytb
Traceback (most recent call last):
  File "/nix/store/07jhm9x8jnikbh6ag9cdf5dszj1j0vjp-steck-0.5.0/bin/.steck-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/1ag2gs5s8l1lyfrlm0813yl0i9g6kilp-python3.7-click-7.1.2/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/1ag2gs5s8l1lyfrlm0813yl0i9g6kilp-python3.7-click-7.1.2/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/nix/store/1ag2gs5s8l1lyfrlm0813yl0i9g6kilp-python3.7-click-7.1.2/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nix/store/1ag2gs5s8l1lyfrlm0813yl0i9g6kilp-python3.7-click-7.1.2/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/1ag2gs5s8l1lyfrlm0813yl0i9g6kilp-python3.7-click-7.1.2/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/07jhm9x8jnikbh6ag9cdf5dszj1j0vjp-steck-0.5.0/lib/python3.7/site-packages/steck.py", line 101, in paste
    filtered = ignored(*paths)
  File "/nix/store/07jhm9x8jnikbh6ag9cdf5dszj1j0vjp-steck-0.5.0/lib/python3.7/site-packages/steck.py", line 41, in ignored
    encoding="utf8",
  File "/nix/store/q732h09azy7lf0j30bnnhdl15p4rxpdy-python3-3.7.7/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/nix/store/q732h09azy7lf0j30bnnhdl15p4rxpdy-python3-3.7.7/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/nix/store/q732h09azy7lf0j30bnnhdl15p4rxpdy-python3-3.7.7/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'git': 'git'
```

Probably just need to add `FileNotFoundError` here: https://github.com/supakeen/steck/blob/master/steck.py#L43

**Comment by supakeen** [comment]
Caught the correct exception as well, fixes this issue.
