### ISSUE TITLE
Partial config file is not handled gracefully

### ISSUE THREAD

**Issue by mweinelt** [supakeen/steck#13]
If I create a `steck.toml` I need to specify all config values, I can't only give partial values, like `base` and defer to the defaults on all other options.

```pytb
Traceback (most recent call last):
  File "/nix/store/nmn43yc2dqv7ri9dq1qqjf34b14ccwg0-steck-0.5.0/bin/.steck-wrapped", line 6, in <module>
    from steck import main
  File "/nix/store/nmn43yc2dqv7ri9dq1qqjf34b14ccwg0-steck-0.5.0/lib/python3.7/site-packages/steck.py", line 80, in <module>
    default=configuration["confirm"],
KeyError: 'confirm'
```

**Comment by supakeen** [comment]
Configuration file is now used as an update instead of overwriting the configuration.
