### ISSUE TITLE
`capture_output` is 3.7+

### ISSUE THREAD

**Issue by SnoopJ** [supakeen/steck#17]
As noted in the [`subprocess` docs](https://docs.python.org/3/library/subprocess.html#subprocess.run), the `capture_output` argument for `subprocess.run()` was added in 3.7.

Trying to run `steck` with a 3.6 interpreter produces a traceback like:

```
Traceback (most recent call last):
  File "/home/snoopjedi/.pyenv/versions/3.6.10/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/snoopjedi/.pyenv/versions/3.6.10/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/snoopjedi/.pyenv/versions/3.6.10/lib/python3.6/site-packages/steck.py", line 180, in <module>
    raise SystemExit(main())
  File "/home/snoopjedi/.pyenv/versions/3.6.10/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/snoopjedi/.pyenv/versions/3.6.10/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/snoopjedi/.pyenv/versions/3.6.10/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/snoopjedi/.pyenv/versions/3.6.10/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/snoopjedi/.pyenv/versions/3.6.10/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/snoopjedi/.pyenv/versions/3.6.10/lib/python3.6/site-packages/steck.py", line 123, in paste
    filtered = ignored(*paths)
  File "/home/snoopjedi/.pyenv/versions/3.6.10/lib/python3.6/site-packages/steck.py", line 42, in ignored
    encoding="utf8",
  File "/home/snoopjedi/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
```

I'll open a PR to fix this, but maybe this is a sign that the project is ready to move the minimum version to 3.6 in anticipation of the EOL later this year :)

**Comment by SnoopJ** [comment]
Not sure what's up with that failure, looks like there's some sort of problem with `poetry-dynamic-versioning` and TravisCI?

**Comment by supakeen** [comment]
It is a problem of `poetry-dynamic-versioning`, merged the PR.
