### ISSUE TITLE
KeyError: 'link'

### ISSUE THREAD

**Issue by mgedmin** [supakeen/steck#34]
Steps to reproduce:

1. `uv tool install steck` (this gave me steck 0.7.0)
2. `echo hello | steck paste -`

What I expect:

- 'hello' is pasted to https://bpa.st and I see a URL to it printed on the console

What I get:

```console
$ echo hello world | steck paste -
Using stdin for input
You are about to paste stdin. Do you want to continue?

Completed paste.
Traceback (most recent call last):
  File "/home/mg/.local/bin/steck", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mg/.local/share/uv/tools/steck/lib/python3.12/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mg/.local/share/uv/tools/steck/lib/python3.12/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/mg/.local/share/uv/tools/steck/lib/python3.12/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mg/.local/share/uv/tools/steck/lib/python3.12/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mg/.local/share/uv/tools/steck/lib/python3.12/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mg/.local/share/uv/tools/steck/lib/python3.12/site-packages/steck.py", line 175, in paste
    print("View link:   ", response["link"])
                           ~~~~~~~~^^^^^^^^
KeyError: 'link'
```

**Comment by supakeen** [comment]
Huh, interesting I'll take a look.
